[package]
name = "splotch"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plot data to HTML"
keywords = ["chart", "graph", "plot", "visualization"]
categories = ["science", "visualization"]
repository = "https://github.com/AldaronLau/splotch"
readme = "README.md"
